name: Test Build Debian
on:
  push:
    branches:
      - master

jobs:
  build_vim3l_mainline_kernel_images:
    name: Build VIM3L Mainline Kernel Images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # Fetch Dependencies
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y make lsb-release qemu-user-static zip

      # Get current date
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +%F | sed 's/-//g')"

      # Build
      - name: Build Image
        run: |
          .github/workflows/build.sh mainline VIM3L Debian

      # Upload Images to GitHub Actions Artifacts
      - name: 'Upload VIM3L Debian Server Mainline Kernel Images'
        uses: actions/upload-artifact@v2
        with:
          name: VIM3L-Debian-Server-Mainline-Kernel-Firmware-${{ steps.date.outputs.date }}
          path: |
            ${{ github.workspace }}/build/images/VIM*-server-*.img.xz

      - name: 'Upload VIM3L Debian Minimal Mainline Kernel Images'
        uses: actions/upload-artifact@v2
        with:
          name: VIM3L-Debian-Minimal-Mainline-Kernel-Firmware-${{ steps.date.outputs.date }}
          path: |
            ${{ github.workspace }}/build/images/VIM*-minimal-*.img.xz

      - name: 'Upload VIM3L Debian Desktop Mainline Kernel Images'
        uses: actions/upload-artifact@v2
        with:
          name: VIM3L-Debian-Desktop-Mainline-Kernel-Firmware-${{ steps.date.outputs.date }}
          path: |
            ${{ github.workspace }}/build/images/VIM*-xfce-*.img.xz

      - name: 'Upload VIM3L Debian Packages for Mainline Kernel'
        uses: actions/upload-artifact@v2
        with:
          name: VIM3L-Debian-Packages-Mainline-Kernel-${{ steps.date.outputs.date }}
          path: |
            ${{ github.workspace }}/build/images/debs/

  build_vim3l_legacy_kernel_images:
    name: Build VIM3L Legacy Kernel Images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # Fetch Dependencies
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y make lsb-release qemu-user-static zip

      # Get current date
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +%F | sed 's/-//g')"

      # Build
      - name: Build Image
        run: |
          .github/workflows/build.sh legacy VIM3L Debian

      # Upload Images to GitHub Actions Artifacts
      - name: 'Upload VIM3L Debian Server Legacy Kernel Images'
        uses: actions/upload-artifact@v2
        with:
          name: VIM3L-Debian-Server-Legacy-Kernel-Firmware-${{ steps.date.outputs.date }}
          path: |
            ${{ github.workspace }}/build/images/VIM*-server-*.img.xz

      - name: 'Upload VIM3L Debian Minimal Legacy Kernel Images'
        uses: actions/upload-artifact@v2
        with:
          name: VIM3L-Debian-Minimal-Legacy-Kernel-Firmware-${{ steps.date.outputs.date }}
          path: |
            ${{ github.workspace }}/build/images/VIM*-minimal-*.img.xz

      - name: 'Upload VIM3L Debian Desktop Legacy Kernel Images'
        uses: actions/upload-artifact@v2
        with:
          name: VIM3L-Debian-Desktop-Legacy-Kernel-Firmware-${{ steps.date.outputs.date }}
          path: |
            ${{ github.workspace }}/build/images/VIM*-xfce-*.img.xz

      - name: 'Upload VIM3L Debian Packages for Legacy Kernel'
        uses: actions/upload-artifact@v2
        with:
          name: VIM3L-Debian-Packages-Legacy-Kernel-${{ steps.date.outputs.date }}
          path: |
            ${{ github.workspace }}/build/images/debs/
